import ImgSushiRoll from "../assets/images/image-sushiroll-menu.jpg";

export const Data = [
  {
    image: ImgSushiRoll,
    title: "California sushi roll with tuna, vegetables and unagi sauce.",
    price: "$1.99",
    deal: "5% off 3 rolls",
    id: "Roll",
  },
  {
    image: ImgSushiRoll,
    title: "Sushi Set",
    price: "$7.99",
    deal: " ",
    id: "Set",
  },
  {
    image: ImgSushiRoll,
    title: "Dessert",
    price: "$2.99",
    deal: " ",
    id: "Dessert",
  },
  {
    image: ImgSushiRoll,
    title: "Vegetarian Rolls",
    price: "$1.99",
    deal: " ",
    id: "Vegetarian",
  },
  {
    image: ImgSushiRoll,
    title: "Beverages",
    price: "$0.99",
    deal: " ",
    id: "Beverage",
  },
  {
    image: ImgSushiRoll,
    title: "California sushi roll with tuna, vegetables and unagi sauce.",
    price: "$1.99",
    deal: "5% off 3 rolls",
    id: "Roll",
  },
  {
    image: ImgSushiRoll,
    title: "Sushi Set",
    price: "$7.99",
    deal: " ",
    id: "Set",
  },
  {
    image: ImgSushiRoll,
    title: "Dessert",
    price: "$2.99",
    deal: " ",
    id: "Dessert",
  },
  {
    image: ImgSushiRoll,
    title: "Vegetarian Rolls",
    price: "$1.99",
    deal: " ",
    id: "Vegetarian",
  },
  {
    image: ImgSushiRoll,
    title: "Beverages",
    price: "$0.99",
    deal: " ",
    id: "Beverage",
  },
  {
    image: ImgSushiRoll,
    title: "California sushi roll with tuna, vegetables and unagi sauce.",
    price: "$1.99",
    deal: "5% off 3 rolls",
    id: "Roll",
  },
  {
    image: ImgSushiRoll,
    title: "Sushi Set",
    price: "$7.99",
    deal: " ",
    id: "Set",
  },
  {
    image: ImgSushiRoll,
    title: "Dessert",
    price: "$2.99",
    deal: " ",
    id: "Dessert",
  },
  {
    image: ImgSushiRoll,
    title: "Vegetarian Rolls",
    price: "$1.99",
    deal: " ",
    id: "Vegetarian",
  },
  {
    image: ImgSushiRoll,
    title: "Beverages",
    price: "$0.99",
    deal: " ",
    id: "Beverage",
  },
  {
    image: ImgSushiRoll,
    title: "California sushi roll with tuna, vegetables and unagi sauce.",
    price: "$1.99",
    deal: "5% off 3 rolls",
    id: "Roll",
  },
  {
    image: ImgSushiRoll,
    title: "Sushi Set",
    price: "$7.99",
    deal: " ",
    id: "Set",
  },
  {
    image: ImgSushiRoll,
    title: "Dessert",
    price: "$2.99",
    deal: " ",
    id: "Dessert",
  },
  {
    image: ImgSushiRoll,
    title: "Vegetarian Rolls",
    price: "$1.99",
    deal: " ",
    id: "Vegetarian",
  },
  {
    image: ImgSushiRoll,
    title: "Beverages",
    price: "$0.99",
    deal: " ",
    id: "Beverage",
  },
];
